campaign/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.urls import re_path as path
from .views import (
    Logout,
    add_contact,
    campaign_view,
    delete_all_contacts,
    delete_contact,
    delete_smtp,
    login_view,
    create_user_view,
    dashboard_view,
    contact_view,
    contact_list,
    contact_create,
    preview_campaign,
    segment_detail,
    segment_create,
    delete_segment,
    SMTPPage,
    AddUpdateSMTP,
    send_campaign,
    test_smtp,
    settings_view,
    add_update_campaign,
)


urlpatterns = [
    path(r'^login/$', login_view, name='login'),
    path(r'^logout/$', Logout, name='logout'),
    path(r'^create_user/$', create_user_view, name='create_user'),
    path(r'^dashboard/$', dashboard_view, name='dashboard'),
    path(r'^$', dashboard_view, name='home'),
    path(r'^contacts/$', contact_view, name='contacts_page'),

    path(r'^manage-contacts/$', contact_list, name='manage-contacts'),
    path(r'^create-segment/$', segment_create, name='create-segment'),
    path(r'^upload-contacts/$', contact_create, name='upload-contacts'),
    path(r'^add-contact/$', add_contact, name='add-contact'),
    path(r'^delete-all/$', delete_all_contacts, name='delete_all_contacts'),
    path(r'^delete-contact/(?P<contact_id>[\w-]+)/$', delete_contact, name='delete_contact'),

    path(r'^segments/detail/(?P<pk>[\w-]+)/', segment_detail, name='segment-detail'),
    path(r'^delete-segment/(?P<segment_id>[\w-]+)/', delete_segment, name='segment-delete'),

    path(r'^smtp-list/$', SMTPPage, name='smtp'),
    path(r'^smtp/$', AddUpdateSMTP, name='add_smtp'),
    path(r'^smtp-test/$', test_smtp, name='test_smtp'),
    path(r'^delete-smtp/(?P<smtp_id>[\w-]+)/$', delete_smtp, name='delete_smtp'),

    path(r'^settings/$', settings_view, name='settings'),
    
    path(r'^campaigns/$', campaign_view, name='campaign_view'),
    path(r'^campaign/$', add_update_campaign, name='add_update_campaign'),
    path(r'^campaign/preview/(?P<campaign_id>[\w-]+)/$', preview_campaign, name='preview_campaign'),
    path(r'^campaign/send/(?P<campaign_id>[\w-]+)/$', send_campaign, name='send_campaign'),
]

web/forms.py
from django import forms
from .models import Campaign, Contact, Segment, ContactList, Settings

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'segment', 'is_active']

class SegmentForm(forms.ModelForm):
    class Meta:
        model = Segment
        fields = ['name']

class ContactListForm(forms.ModelForm):
    class Meta:
        model = ContactList
        fields = ['name', 'contacts', 'subscription_management']


class SMTPForm(forms.Form):
    host = forms.CharField(max_length=255)
    port = forms.IntegerField()
    sender_name = forms.CharField(max_length=255)
    sender_email = forms.CharField(max_length=255)
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput)
    use_tls = forms.BooleanField(required=False)
    use_ssl = forms.BooleanField(required=False)


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Settings
        fields = ['email_tag', 'name_tag', 'time_tag', 'date_tag', 'clock_type']

class CampaignForm(forms.ModelForm):
    attachment_content = forms.CharField(widget=forms.Textarea, required=False, label="Attachment Content")
    sender_type = forms.ChoiceField(choices=Campaign.SENDER_CHOICES, required=True, label="Sender Type")
    # attachment_type = forms.ChoiceField(choices=[('html', 'HTML'), ('pdf', 'PDF')], required=True, label="Attachment Type")
    filename = forms.CharField(required=False, label="Attachment Filename")

    class Meta:
        model = Campaign
        fields = ['campaign_name', 'subject', 'content', 'attachment_content', 'segment', 'smtp', 'filename', 'sender_type']

web/templates/add_contact.html
{% extends "app.html" %}

{% block app %}
<div class="container-fluid">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-lg-12">
               <div class="d-flex align-items-center border-bottom justify-content-between mb-4">
                  <div class="form-name">
                     <h3 class="mb-2">Add a Contact</h3>
                  </div>
                  
               </div>
            </div>
         </div>
         <div class="row">
            <div class="col-lg-12">
               <div class="tab-content">
                  <div id="pill-1" class="tab-pane fade active show">
                     <div class="row">
                        <div class="col-sm-12">
                           <form class="form-contact">
                            {% csrf_token %}
                              <div class="row">
                                 <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                       <label class="mb-0">Full Name</label>
                                       <input class="form-control" type="text" placeholder="Enter full name" name="name" required>
                                    </div>
                                 </div>
                                 <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                       <label class="mb-0">Email</label>
                                       <input class="form-control" type="email" placeholder="Enter email" name="email" required>
                                    </div>
                                 </div>
                                 <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                       <label class="mb-0">Segment</label>
                                       <select name="segment" class="selectpicker form-control" data-style="py-0" required>
                                          <option value="">Select Segment</option>
                                          {% for segment in segments %}
                                          <option value="{{segment.pk}}">{{segment.name}}</option>
                                          {% endfor %}
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <button type="submit" class="btn btn-primary btn-save-contact btn-lg mt-4">Save Contact</button>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Page end  -->
</div>
{% endblock app %}

web/templates/app.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>EmailCHIMP | Responsive Bootstrap 4 Admin Dashboard Template</title>
      
      <!-- Favicon -->
      <link rel="shortcut icon" href="https://templates.iqonic.design/emailchimp/html/assets/images/favicon.ico" />
      <link rel="stylesheet" href="/static/css/backend-plugin.min.css">
      <link rel="stylesheet" href="/static/css/backend9f1e.css?v=1.1.0">
      <link rel="stylesheet" href="/static/vendor/%40fortawesome/fontawesome-free/css/all.min.css">
      <link rel="stylesheet" href="/static/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css">
      <link rel="stylesheet" href="/static/vendor/remixicon/fonts/remixicon.css">
      <link rel="stylesheet" href="/static/vendor/%40icon/dripicons/dripicons.css">
      
      <link rel='stylesheet' href='/static/vendor/fullcalendar/core/main.css' />
      <link rel='stylesheet' href='/static/vendor/fullcalendar/daygrid/main.css' />
      <link rel='stylesheet' href='/static/vendor/fullcalendar/timegrid/main.css' />
      <link rel='stylesheet' href='/static/vendor/fullcalendar/list/main.css' />
      <link rel="stylesheet" href="/static/vendor/mapbox/mapbox-gl.css">
      <style>

        #analog-clock {
            position: relative;
            bottom: 0;
            left: 50%;
            width: 200px;
            height: 200px;
            transform: translate(-50%, 40%);
            border: 10px solid #333;
            border-radius: 50%;
            background: white;
            z-index: -1;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            font-family: 'Arial', sans-serif;
        }

        #analog-clock::after {
            content: "Ohunayo";
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 24px;
            font-weight: bold;
            color: #999;
        }

        .hand {
            z-index: 1;
            position: absolute;
            width: 30%;
            height: 6px;
            background: black;
            top: 50%;
            left: 20%;
            transform-origin: 100%;
            transform: rotate(90deg);
            transition: all 0.05s cubic-bezier(0.4, 2.3, 0.3, 1);
        }

        .minute-hand {
            height: 4px;
            background: blue;
        }

        .second-hand {
            height: 2px;
            background: red;
        }

        .clock-text {
            position: absolute;
            font-size: 12px;
            font-weight: bold;
        }

        .clock-text.top {
            top: 10%;
        }

        .clock-text.bottom {
            bottom: 10%;
        }

        .clock-text.left {
            left: 10%;
        }

        .clock-text.right {
            right: 10%;
        }

        #digital-clock-container {
            position: relative;
            bottom: 0;
            transform: translate(5%, 100%);
            font-family: 'Courier New', Courier, monospace;
            margin: 20px auto;
            padding: 15px;
            background: #f0f0f0;
            border: 5px solid #333;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.2);

        }
        #digital-clock {
            font-size: 28px;
            color: #333;
            font-weight: bold;
        }

        #clock-name {
            font-size: 14px;
            color: #666;
            margin-top: 5px;
            text-align: center;
        }
    </style>
</head>
  <body class="email-chimp">
    <!-- loader Start -->
    <div id="loading">
          <div id="loading-center"></div>
    </div>
    <!-- loader END -->

    <!-- Wrapper Start -->
    <div class="wrapper">
        {% include "sidebar.html" %}
        <div class="content-page">
            {% block app %}{% endblock app %}
        </div>
    </div>
    <!-- Wrapper End-->
    <footer class="iq-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="privacy-policy.html">Privacy Policy</a></li>
                        <li class="list-inline-item"><a href="terms-of-service.html">Terms of Use</a></li>
                    </ul>
                </div>
                <div class="col-lg-6 text-right">
                    Copyright <span id="copyright"> 
                    <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script>
                    </span> <a href="#">EmailCHIMP</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Backend Bundle JavaScript -->
    <script src="/static/js/backend-bundle.min.js"></script>
    <!-- Flextree Javascript-->
    <!-- Table Treeview JavaScript -->
    <script src="/static/js/table-treeview.js"></script>
    <!-- Masonary Gallery Javascript -->
    
    <!-- Mapbox Javascript -->
    <!-- Fullcalender Javascript -->
    <script src='/static/vendor/fullcalendar/core/main.js'></script>
    <script src='/static/vendor/fullcalendar/daygrid/main.js'></script>
    <script src='/static/vendor/fullcalendar/timegrid/main.js'></script>
    <script src='/static/vendor/fullcalendar/list/main.js'></script>
    
    <!-- SweetAlert JavaScript -->
    <script src="/static/js/sweetalert.js"></script>
    
    <!-- Vectoe Map JavaScript -->
    <script src="/static/js/vector-map-custom.js"></script>
    
    <!-- Chart Custom JavaScript -->
    
    <!-- Chart Custom JavaScript -->
    <script src="/static/js/chart-custom.js"></script>
    
    <!-- slider JavaScript -->
    <script src="/static/js/slider.js"></script>
    
    <!-- app JavaScript -->
    <script src="/static/js/app.js"></script>

    
  </body>
</html>

web/templates/contact_form.html
{% extends "app.html" %}

{% block app %}
<style>
    .not-visible{
        display: none;
    }
</style>
<div class="container-fluid">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-lg-12">
               <div class="d-flex align-items-center border-bottom justify-content-between mb-4">
                  <div class="form-name">
                     <h3 class="mb-2">Upload Contacts</h3>
                  </div>
               </div>
            </div>
         </div>
         <div class="row">
            <div class="col-lg-12">
               <div class="tab-content">
                  <div id="pill-1" class="tab-pane fade active show">
                     <div class="row">
                        <div class="col-sm-12">
                           <form class="form-contacts" id="upload_form">
                            {% csrf_token %}
                              <div class="row">
                                 <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                       <label class="mb-0">Select File (TXT)</label>
                                       {% comment %} Let's have upload file restricted to txt files alone {% endcomment %}
                                       <input class="form-control" type="file" name="file" id="id_image" accept=".txt" required>
                                    </div>
                                 </div>
                                 <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                       <label class="mb-0">Segment</label>
                                       <select name="segment" class="selectpicker form-control" data-style="py-0" required>
                                          <option value="">Select Segment</option>
                                          {% for segment in segments %}
                                          <option value="{{segment.pk}}">{{segment.name}}</option>
                                          {% endfor %}
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="container not-visible progress" id="progress"></div>
                              <button type="submit" class="btn btn-primary btn-save-contacts btn-lg mt-4">Upload Contacts</button>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Page end  -->
</div>
{% endblock app %}

web/templates/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>EmailCHIMP | Responsive Bootstrap 4 Admin Dashboard Template</title>
      
      <!-- Favicon -->
      <link rel="shortcut icon" href="https://templates.iqonic.design/emailchimp/html/assets/images/favicon.ico" />
      <link rel="stylesheet" href="/static/css/backend-plugin.min.css">
      <link rel="stylesheet" href="/static/css/backend9f1e.css?v=1.1.0">
      <link rel="stylesheet" href="/static/vendor/%40fortawesome/fontawesome-free/css/all.min.css">
      <link rel="stylesheet" href="/static/vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css">
      <link rel="stylesheet" href="/static/vendor/remixicon/fonts/remixicon.css">
      <link rel="stylesheet" href="/static/vendor/%40icon/dripicons/dripicons.css">
      
      <link rel='stylesheet' href='/static/vendor/fullcalendar/core/main.css' />
      <link rel='stylesheet' href='/static/vendor/fullcalendar/daygrid/main.css' />
      <link rel='stylesheet' href='/static/vendor/fullcalendar/timegrid/main.css' />
      <link rel='stylesheet' href='/static/vendor/fullcalendar/list/main.css' />
      <link rel="stylesheet" href="/static/vendor/mapbox/mapbox-gl.css">
</head>
  <body class=" ">
    <!-- loader Start -->
    <div id="loading">
          <div id="loading-center">
          </div>
    </div>
    <!-- loader END -->
    
      <div class="wrapper">
      <section class="login-content">
         <div class="container h-100">
            <div class="row align-items-center justify-content-center h-100">
               <div class="col-12">
                  <div class="row align-items-center">
                     <div class="col-lg-6">
                        <h2 class="mb-2">Create User</h2>
                        <p>Enter your personal details.</p>
                        <form class="form-create-user">
                            {% csrf_token %}
                           <div class="row">
                              <div class="col-lg-6">
                                 <div class="form-group">
                                    <label class="mb-0">First Name</label>
                                    <input class="form-control" type="text" placeholder="First Name" name="first_name" required>
                                    
                                 </div>
                              </div>
                              <div class="col-lg-6">
                                 <div class="form-group">
                                    <label class="mb-0">Last Name</label>
                                    <input class="form-control" type="text" placeholder="Last Name" name="last_name" required>
                                    
                                 </div>
                              </div>
                              <div class="col-lg-12">
                                 <div class="form-group">
                                    <label class="mb-0">Email</label>
                                    <input class="form-control" name="email" type="email" placeholder="Email Address" required>
                                    
                                 </div>
                              </div>
                           </div>
                           <button type="submit" class="btn btn-primary btn-lg btn-create-user">Proceed</button>
                        </form>
                     </div>
                     <div class="col-lg-6 mb-lg-0 mb-4 mt-lg-0 mt-4">
                        <img src="/static/images/login/01.png" class="img-fluid w-80" alt="">
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      </div>
    
    <!-- Backend Bundle JavaScript -->
    <script src="/static/js/backend-bundle.min.js"></script>
    
    <!-- Flextree Javascript-->
    
    <!-- Table Treeview JavaScript -->
    <script src="/static/js/table-treeview.js"></script>
    
    <!-- Masonary Gallery Javascript -->
    
    <!-- Mapbox Javascript -->
    
    <!-- Fullcalender Javascript -->
    <script src='/static/vendor/fullcalendar/core/main.js'></script>
    <script src='/static/vendor/fullcalendar/daygrid/main.js'></script>
    <script src='/static/vendor/fullcalendar/timegrid/main.js'></script>
    <script src='/static/vendor/fullcalendar/list/main.js'></script>
    
    <!-- SweetAlert JavaScript -->
    <script src="/static/js/sweetalert.js"></script>
    
    <!-- Vectoe Map JavaScript -->
    <script src="/static/js/vector-map-custom.js"></script>
    
    <!-- Chart Custom JavaScript -->
    
    <!-- Chart Custom JavaScript -->
    <script src="/static/js/chart-custom.js"></script>
    
    <!-- slider JavaScript -->
    <script src="/static/js/slider.js"></script>
    
    <!-- app JavaScript -->
    <script src="/static/js/app.js"></script>
  </body>
</html>

web/templates/dashboard.html
{% extends "app.html" %}

{% block app %}
<div class="container-fluid">
    <div class="d-grid grid-cols-2 custom-grid-media">
        <div class="">
            <div class="card border subs-card">
                <div class="card-body">
                <div class="">
                    <div class="">
                        <h2 class="mb-2">Hi, {{user.first_name}} {{user.last_name}}</h2>
                        <p class="pb-3">Welcome all your new subscribers. It’s good to have you here!</p>
                    </div>
                    <div class="d-flex flex-wrap align-items-center mt-4">
                        <a class="btn btn-lg btn-primary mr-3" href="{% url 'add_update_campaign' %}">Create Campaign</a>
                        <a class="btn btn-lg btn-transparent explore" href="{% url 'campaign_view' %}">Explore All Campaigns<i class="ri-arrow-right-line ml-2 mt-1"></i></a>
                    </div>
                </div>
                <div class="subs-image">
                    <img src="/static/images/layouts/banner.png" alt="user-image" class="img-fluid">
                </div>
                </div>
            </div>
        </div>
        <div class="right-list index-list-scrollbar">
            <a href="{% url 'contacts_page' %}" title="Contacts">
                <div class="media iq-option border align-items-center p-3">
                <div class="bg-success-light rounded p-4">
                    <img src="/static/images/options/01.png" class="img-fluid avatar-50" alt="image">
                </div>
                <div class="media-body">
                    <h4 class="mb-2">Upload Contacts</h4>
                    <p class="mb-0">Upload all your records from your current system, and import them here.</p>
                </div>
                </div>
            </a>
            <a href="{% url 'create-segment' %}" title="">
                <div class="media iq-option border align-items-center p-3">
                <div class="bg-danger-light rounded p-4">
                    <img src="/static/images/options/02.png" class="img-fluid avatar-50" alt="image">
                </div>
                <div class="media-body">
                    <h4 class="mb-2">Create Segment</h4>
                    <p class="mb-0">Create a page, design it as you like, save it as a template and use for further work.</p>
                </div>
                </div>
            </a>
            <a href="{% url 'add-contact' %}" title="">
                <div class="media iq-option border align-items-center p-3">
                <div class="bg-success-light rounded p-4">
                    <img src="/static/images/options/03.png" class="img-fluid avatar-50" alt="image">
                </div>
                <div class="media-body">
                    <h4 class="mb-2">Add Contact</h4>
                    <p class="mb-0">Create and send your email campaign in literally minutes with a few quick steps.</p>
                </div>
                </div>
            </a>
            {% comment %} <a href="page-integration.html" title="">
                <div class="media iq-option border align-items-center p-3">
                <div class="bg-info-light rounded p-4">
                    <img src="/static/images/options/04.png" class="img-fluid avatar-50" alt="image">
                </div>
                <div class="media-body">
                    <h4 class="mb-2">Verify domain</h4>
                    <p class="mb-0">Verify your company's domain to prove that you own all user accounts with that domain.</p>
                </div>
                </div>
            </a> {% endcomment %}
            <a href="https://paystack.com/pay/buymecoffee-ohunayo" title="" target="_blank">
                <div class="media iq-option active border align-items-center p-3">
                <div class="bg-warning-light rounded p-4">
                    <img src="/static/images/options/08.png" class="img-fluid avatar-50" alt="image">
                </div>
                <div class="media-body">
                    <h4 class="mb-2">Buy Me Coffee</h4>
                    <p class="mb-0">Boost your sales and level up your business with our expert overview options.</p>
                </div>
                </div>
            </a>
        </div>
    </div>
    <!-- Page end  -->
</div>
{% endblock app %}

web/templates/smtp-add-update.html
{% extends "app.html" %}

{% block app %}
<div class="container-fluid">
   <div class="card">
      <div class="card-body">
         <div class="row">
            <div class="col-lg-12">
               <div class="d-flex align-items-center border-bottom justify-content-between mb-4">
                  <div class="form-name">
                     <h3 class="mb-2">{{ form_title }}</h3>
                  </div>
               </div>
            </div>
         </div>
         <div class="row">
            <div class="col-lg-12">
               <div class="tab-content">
                  <div id="pill-1" class="tab-pane fade active show">
                     <div class="row">
                        <div class="col-sm-12">
                           <form id="smtp-form" class="form-smtp">
                              {% csrf_token %}
                              <input type="hidden" name="id" value="{{ smtp_setting.id }}">
                              <div class="row">
                                 <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                       <label class="mb-0">SMTP Host</label>
                                       <input class="form-control" type="text" placeholder="Enter SMTP host" name="host" value="{{ smtp_setting.host }}" required>
                                       <div class="text-danger" id="error-host" style="display: none;"></div>
                                    </div>
                                 </div>
                                 <div class="col-lg-3 col-md-3">
                                    <div class="form-group">
                                       <label class="mb-0">Port</label>
                                       <input class="form-control" type="number" placeholder="Enter port" name="port" value="{{ smtp_setting.port }}" required>
                                       <div class="text-danger" id="error-port" style="display: none;"></div>
                                    </div>
                                 </div>
                                 <div class="col-lg-3 col-md-3">
                                    <div class="form-group">
                                       <label class="mb-0">Username</label>
                                       <input class="form-control" type="text" placeholder="Enter username" name="username" value="{{ smtp_setting.username }}" required>
                                       <div class="text-danger" id="error-username" style="display: none;"></div>
                                    </div>
                                 </div>
                                 <div class="col-lg-6 col-md-6">
                                    <div class="form-group">
                                       <label class="mb-0">Password</label>
                                       <input class="form-control" type="text" placeholder="Enter password" name="password" value="{{ smtp_setting.password }}" required>
                                       <div class="text-danger" id="error-password" style="display: none;"></div>
                                    </div>
                                 </div>
                                 <div class="col-lg-3 col-md-3">
                                    <div class="form-group">
                                       <label class="mb-0">Default Sender Name</label>
                                       <input class="form-control" type="text" placeholder="Enter sender name" name="sender_name" value="{{ smtp_setting.sender_name }}">
                                       <div class="text-danger" id="error-sender_name" style="display: none;"></div>
                                    </div>
                                 </div>
                                 <div class="col-lg-3 col-md-3">
                                    <div class="form-group">
                                       <label class="mb-0">Default Sender Email</label>
                                       <input class="form-control" type="email" placeholder="Enter sender email" name="sender_email" value="{{ smtp_setting.sender_email }}">
                                       <div class="text-danger" id="error-sender_email" style="display: none;"></div>
                                    </div>
                                 </div>
                                 <div class="col-lg-6 col-md-6">
                                    <div class="form-check">
                                       <input type="checkbox" name="use_tls" id="id_use_tls" class="form-check-input" {% if smtp_setting.use_tls %}checked{% endif %}>
                                       <label for="id_use_tls" class="form-check-label">Use TLS</label>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-check">
                                       <input type="checkbox" name="use_ssl" id="id_use_ssl" class="form-check-input" {% if smtp_setting.use_ssl %}checked{% endif %}>
                                       <label for="id_use_ssl" class="form-check-label">Use SSL</label>
                                    </div>
                                </div>
                              </div>
                              <button type="submit" class="btn btn-primary btn-save-smtp btn-lg mt-4">Save SMTP</button>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Page end -->
</div>
{% endblock app %}